a=int(input("enter first number"))
b=int(input("enter second number"))
print("the sum of the two numbers is",a+b)
print("the substraction of the two numbers is",a-b)
print("the multiplication of the two numbers is",a*b)
print("the floor division of the two numbers is",a//b)
print("the integer division of the two numbers is",a/b)
print("the module of the two numbers is",a%b)
